-- Hyprland config, migrated from hyprland.conf (hyprlang) to Lua for 0.55+.
-- Wiki: https://wiki.hypr.land/Configuring/Start/
--
-- RECOVERY: if Hyprland ever fails to start, drop to a TTY (Ctrl+Alt+F2) and run:
--     ~/.config/hypr/restore-lua.sh
-- That restores hyprland.lua.original (pristine, read-only). Renaming or deleting
-- hyprland.lua also works -- Hyprland then falls back to hyprland.conf.
--
-- DO NOT set the AQ DRM device-override env var here. Doing so hung Hyprland's
-- init on 2026-08-08 (watchdog SIGABRT in initServer). Aquamarine already
-- enumerates both GPUs and selects card1/amdgpu on its own, so the override is
-- unnecessary. Env vars also cannot be validated by `hyprctl reload` -- they
-- only take effect at compositor startup, i.e. a real login.

--------------
---- SKIN ----
--------------

-- Window border colours come from the active skin rather than being written
-- here. ~/.local/state/skins/skin.lua is generated by `skinctl` and returns a
-- flat table of bare rrggbb strings; the source it is generated from is
-- ~/.config/skins/skins.toml.
--
-- The load is wrapped in pcall on purpose. This file is the compositor's
-- entire configuration, and a missing or half-written skin.lua raising out of
-- a bare dofile would take the whole session down to a black screen on a
-- machine whose recovery path is a TTY. Falling back to the Ember values
-- below costs nothing and cannot fail.
local skin = (function()
    local state = os.getenv("XDG_STATE_HOME") or (os.getenv("HOME") .. "/.local/state")
    local ok, loaded = pcall(dofile, state .. "/skins/skin.lua")
    if ok and type(loaded) == "table" and loaded.outer then
        return loaded
    end
    return {
        outer   = "f96b69",  -- Ember: the sun disc
        accent  = "e8a04a",  -- Ember: amber
        inner   = "482b2c",  -- Ember: the horizon band
        shadow  = "0f0c0e",
    }
end)()

-- Hyprland wants rgba(rrggbbaa); the skin table stores rrggbb.
local function rgba(token, alpha)
    return "rgba(" .. token .. (alpha or "ff") .. ")"
end


------------------
---- MONITORS ----
------------------

-- Internal panel at 60Hz: the iGPU sat at 40-50% busy just compositing at 144Hz.
-- Set mode = "1920x1080@144" to revert.
-- Panel is 1920x1080 across 310mm = 157 DPI, but toolkits assume 96 DPI, so at
-- scale 1 everything rendered at 61% of intended size. 1.5 divides cleanly
-- (1920/1.5 = 1280, 1080/1.5 = 720, both integers -- Hyprland rejects scales
-- that produce a fractional logical resolution). 1.6 is closer to the true
-- 96/157 correction if 1.5 still reads small. Set back to 1 to revert.
hl.monitor({
    output   = "eDP-1",
    mode     = "1920x1080@60",
    position = "0x0",
    scale    = 1.5,
})

-- Catch-all for external displays. was: monitor=,preferred,auto,1
hl.monitor({
    output   = "",
    mode     = "preferred",
    position = "auto",
    scale    = 1,
})


---------------------
---- MY PROGRAMS ----
---------------------

-- hyprlang's $vars are just Lua locals now.
local terminal    = "kitty"
local fileManager = "nautilus"
-- The application menu is the Quickshell launcher now, bound below; wofi is
-- still installed for the clipboard picker on SUPER + V. Restore
-- `local menu = "wofi --show drun"` and point SUPER + space back at it to
-- undo that.


-------------------
---- AUTOSTART ----
-------------------

hl.on("hyprland.start", function()
    -- swaync is deliberately NOT here. It ships a systemd unit with
    -- Restart=on-failure and a D-Bus name (org.freedesktop.Notifications).
    -- Starting it as a bare process here meant the unit and the process raced
    -- for that name every login: the loser exited 1, systemd retried it five
    -- times and gave up with start-limit-hit, leaving a permanently failed
    -- unit next to a working daemon. It is enabled into
    -- graphical-session.target.wants now and systemd owns it alone.
    -- waybar and hyprpaper retired 2026-08-19: the status bar is the
    -- Quickshell surface (Bar.qml, handoff turn 13b) and the wallpaper is
    -- the battle field (Wallpaper.qml, turn 16a), which owns the background
    -- layer itself. Their configs stay in the repo but nothing starts them.
    hl.exec_cmd("hypridle")

    -- The Quickshell shell, currently hosting the RPG launcher (SUPER + space).
    -- -d detaches it from this process. It stays resident with no window
    -- shown: the launcher surface is built once at startup and toggled over
    -- IPC, so opening it costs a frame rather than a process start, and
    -- nothing in it polls or animates while it is hidden.
    hl.exec_cmd("qs -d")

    -- Bring up the session's systemd units.
    --
    -- This used to read "that target never activates under this launcher, so
    -- start the unit directly", and started hyprpolkitagent.service and
    -- hyprsunset.service by name. That was never quite the real story:
    -- hyprsunset.service has Requires=graphical-session.target, so starting
    -- hyprsunset is what dragged the target up, and the target in turn started
    -- the polkit agent, the xdg portals and everything else in its .wants
    -- directory. The whole session hung off a side effect of one
    -- blue-light-filter unit.
    --
    -- graphical-session.target cannot be started by name -- it sets
    -- RefuseManualStart=yes and only comes up as someone's dependency. So
    -- hyprland-session.target exists to be that someone. See
    -- ~/.config/systemd/user/hyprland-session.target.
    hl.exec_cmd("systemctl --user start hyprland-session.target")

    hl.exec_cmd("wl-paste --type text --watch cliphist store")   -- text only
    hl.exec_cmd("wl-paste --type image --watch cliphist store")  -- images only

    -- Keep the selection alive after the source window closes. Without this,
    -- Wayland drops the clipboard when the owning client exits and a plain
    -- Ctrl+V pastes nothing. "regular" only -- covering primary as well is
    -- known to fight cliphist over the middle-click selection.
    hl.exec_cmd("wl-clip-persist --clipboard regular")

    -- was: exec-once = [workspace 1 silent] firefox
    -- Dispatcher prefixes are now the rules table on exec_cmd.
    hl.dispatch(hl.dsp.exec_cmd("firefox", { workspace = "1 silent" }))
    hl.dispatch(hl.dsp.exec_cmd(terminal,  { workspace = "2 silent" }))
end)


-------------------------------
---- ENVIRONMENT VARIABLES ----
-------------------------------

-- 24 is the standard base size. These were at 32 to hand-compensate for the
-- 157 DPI panel; the monitor scale of 1.5 now does that, and 32 would render
-- as an effective 48.
hl.env("XCURSOR_SIZE", "24")
hl.env("HYPRCURSOR_SIZE", "24")

-- Electron apps (Discord, VS Code) default to Xwayland, where the compositor
-- can only bitmap-upscale them: right size, but soft at scale 1.5. This makes
-- them native Wayland so they render sharp. "auto" falls back to X11 when
-- there is no Wayland display, so it is safe outside Hyprland too.
-- /usr/bin/discord reads no flags file, unlike /usr/bin/code -- hence the env
-- var rather than ~/.config/*-flags.conf. Needs Electron 28+; Discord 1.0.153
-- ships Chrome/148, well past that.
hl.env("ELECTRON_OZONE_PLATFORM_HINT", "auto")
-- $HOME isn't expanded for you anymore; this is plain Lua.
hl.env("HYPRSHOT_DIR", os.getenv("HOME") .. "/Pictures/clipboard")


-----------------------
----- PERMISSIONS -----
-----------------------

-- hl.config({
--     ecosystem = {
--         enforce_permissions = true,
--     },
-- })

-- hl.permission("/usr/(bin|local/bin)/grim", "screencopy", "allow")
-- hl.permission("/usr/(lib|libexec|lib64)/xdg-desktop-portal-hyprland", "screencopy", "allow")
-- hl.permission("/usr/(bin|local/bin)/hyprpm", "plugin", "allow")


-----------------------
---- LOOK AND FEEL ----
-----------------------

hl.config({
    general = {
        -- Chunky pass. Gaps are wide enough that the wallpaper reads as a
        -- frame around the windows rather than a sliver between them, and
        -- gaps_out is no longer 0, so windows stop touching the screen edge
        -- and the bar. Back to 5/0/2 for the previous tight look.
        gaps_in  = 6,
        gaps_out = 12,

        border_size = 4,

        -- col.active_border is now a nested table; gradients are
        -- { colors = {...}, angle = deg }
        --
        -- The focused border runs the skin's frame colour into its accent --
        -- under Ember that is the sun disc into amber, where it used to be
        -- the sun disc into its reflection (rgba(d4525aff)), which the token
        -- set has no name for. The inactive border is `inner`, the same
        -- colour the design uses for every rule and empty meter track:
        -- visible against the wallpaper, but far enough down in brightness
        -- that only one window ever looks focused.
        col = {
            active_border   = { colors = { rgba(skin.outer), rgba(skin.accent) }, angle = 45 },
            inactive_border = rgba(skin.inner),
        },

        resize_on_border = false,
        allow_tearing    = false,

        layout = "dwindle",
    },

    decoration = {
        -- Square corners are half of the chunky look; the 4px border above is
        -- the other half. rounding_power is inert while rounding is 0 and is
        -- kept only so restoring rounding = 10 restores the old shape exactly.
        rounding       = 0,
        rounding_power = 2,

        active_opacity   = 1.0,
        inactive_opacity = 1.0,

        -- A hard offset shadow rather than a soft halo: sharp turns off the
        -- gaussian falloff, so this renders as a solid slab displaced down and
        -- right, the way a sticker sits above paper. render_power is ignored
        -- while sharp is true. Previous soft shadow was range 4, power 3, no
        -- offset.
        shadow = {
            enabled      = true,
            sharp        = true,
            range        = 10,
            offset       = "6 6",
            render_power = 3,
            -- dd is the alpha the soft-shadow version used and is kept; the
            -- colour itself is the skin's `shadow` token, which exists for
            -- exactly this -- the halo and hard drop shadow under every frame.
            color        = rgba(skin.shadow, "dd"),
        },

        blur = {
            enabled  = false,
            size     = 3,
            passes   = 1,
            vibrancy = 0.1696,
        },
    },

    animations = {
        -- Off: transitions force full-rate redraws, which defeats VRR while they
        -- play. Set back to true to restore; the hl.animation() curves below are
        -- kept intact and simply ignored while this is false.
        enabled = false, -- was: enabled = yes, please :)
    },

    dwindle = {
        -- pseudotile = true,
        preserve_split = true,
    },

    master = {
        new_status = "master",
    },

    misc = {
        force_default_wallpaper = -1,
        disable_hyprland_logo   = false,

        -- Adaptive sync: stop redrawing a static screen at full refresh rate.
        vrr = 1,

        -- Required by the `fixlock` script. If hyprlock stops taking input, the
        -- ext-session-lock protocol keeps the compositor locked with no client
        -- to type into; without this, killing hyprlock cannot hand the lock to a
        -- fresh instance and the only way out is a reboot.
        allow_session_lock_restore = true,
    },
})


-- Beziers are hl.curve() now, and take point pairs instead of four flat floats.
hl.curve("easeOutQuint",   { type = "bezier", points = { { 0.23, 1 },    { 0.32, 1 }   } })
hl.curve("easeInOutCubic", { type = "bezier", points = { { 0.65, 0.05 }, { 0.36, 1 }   } })
hl.curve("linear",         { type = "bezier", points = { { 0, 0 },       { 1, 1 }      } })
hl.curve("almostLinear",   { type = "bezier", points = { { 0.5, 0.5 },   { 0.75, 1.0 } } })
hl.curve("quick",          { type = "bezier", points = { { 0.15, 0 },    { 0.1, 1 }    } })

hl.animation({ leaf = "global",        enabled = true, speed = 10,   bezier = "default" })
hl.animation({ leaf = "border",        enabled = true, speed = 5.39, bezier = "easeOutQuint" })
hl.animation({ leaf = "windows",       enabled = true, speed = 4.79, bezier = "easeOutQuint" })
hl.animation({ leaf = "windowsIn",     enabled = true, speed = 4.1,  bezier = "easeOutQuint", style = "popin 87%" })
hl.animation({ leaf = "windowsOut",    enabled = true, speed = 1.49, bezier = "linear",       style = "popin 87%" })
hl.animation({ leaf = "fadeIn",        enabled = true, speed = 1.73, bezier = "almostLinear" })
hl.animation({ leaf = "fadeOut",       enabled = true, speed = 1.46, bezier = "almostLinear" })
hl.animation({ leaf = "fade",          enabled = true, speed = 3.03, bezier = "quick" })
hl.animation({ leaf = "layers",        enabled = true, speed = 3.81, bezier = "easeOutQuint" })
hl.animation({ leaf = "layersIn",      enabled = true, speed = 4,    bezier = "easeOutQuint", style = "fade" })
hl.animation({ leaf = "layersOut",     enabled = true, speed = 1.5,  bezier = "linear",       style = "fade" })
hl.animation({ leaf = "fadeLayersIn",  enabled = true, speed = 1.79, bezier = "almostLinear" })
hl.animation({ leaf = "fadeLayersOut", enabled = true, speed = 1.39, bezier = "almostLinear" })
hl.animation({ leaf = "workspaces",    enabled = true, speed = 0.3,  bezier = "almostLinear", style = "fade" })
hl.animation({ leaf = "workspacesIn",  enabled = true, speed = 0.3,  bezier = "almostLinear", style = "fade" })
hl.animation({ leaf = "workspacesOut", enabled = true, speed = 0.3,  bezier = "almostLinear", style = "fade" })


-- "Smart gaps" / "No gaps when only" -- uncomment if you want it.
-- hl.workspace_rule({ workspace = "w[tv1]", gaps_out = 0, gaps_in = 0 })
-- hl.workspace_rule({ workspace = "f[1]",   gaps_out = 0, gaps_in = 0 })
-- hl.window_rule({
--     name  = "no-gaps-wtv1",
--     match = { float = false, workspace = "w[tv1]" },
--     border_size = 0,
--     rounding    = 0,
-- })
-- hl.window_rule({
--     name  = "no-gaps-f1",
--     match = { float = false, workspace = "f[1]" },
--     border_size = 0,
--     rounding    = 0,
-- })


---------------
---- INPUT ----
---------------

hl.config({
    input = {
        kb_layout  = "us",
        kb_variant = "",
        kb_model   = "",
        kb_options = "",
        kb_rules   = "",

        follow_mouse = 1,
        sensitivity  = 0.4, -- -1.0 to 1.0, 0 means no modification

        touchpad = {
            natural_scroll       = true,
            clickfinger_behavior = true, -- was 1; this is a bool now
            tap_and_drag         = false, -- was tap-and-drag = no; hyphen -> underscore
            drag_lock            = 0,     -- was no; this is an int now (0/1/2)
        },

        accel_profile = "flat",
    },
})

-- Per-device config
hl.device({
    name          = "logitech-wireless-receiver-mouse",
    sensitivity   = 0,
    accel_profile = "flat",
})

hl.device({
    name          = "yichip-wireless-device-mouse",
    sensitivity   = -0.1,
    accel_profile = "flat",
})


---------------------
---- KEYBINDINGS ----
---------------------

local mainMod = "SUPER"

hl.bind(mainMod .. " + Return", hl.dsp.exec_cmd(terminal))
-- Was SUPER + C. W for "window" is the closer analogue to what every other
-- application uses to close a tab or a window.
hl.bind(mainMod .. " + W",      hl.dsp.window.close())
hl.bind(mainMod .. " + E",      hl.dsp.exec_cmd(fileManager))
hl.bind(mainMod .. " + B",      hl.dsp.exec_cmd("firefox"))
-- The RPG launcher, from the Quickshell shell started above. It opens on the
-- four favourites and searches every installed .desktop entry as soon as you
-- type, so it replaces what wofi was bound here for.
--
-- Was: hl.dsp.exec_cmd(menu), i.e. `wofi --show drun`. wofi is still
-- installed and still used by the clipboard picker on SUPER + V; only the
-- application menu moved.
hl.bind(mainMod .. " + space",  hl.dsp.exec_cmd("qs ipc call launcher toggle"))
hl.bind(mainMod .. " + F",      hl.dsp.window.fullscreen())
-- hl.bind(mainMod .. " + V", hl.dsp.window.float({ action = "toggle" }))
-- hl.bind(mainMod .. " + J", hl.dsp.layout("togglesplit"))

-- SUPER+P was window.pseudo(). Dropped -- dwindle's `pseudotile` is commented
-- out in the layout config below, so the dispatcher had nothing to toggle.
-- The key now belongs to hyprpicker, further down.

-- Log out. Bound to L so it reads as the counterpart of SUPER+L (lock, below):
-- same key, SHIFT for the version you cannot undo. Lock keeps the session,
-- SHIFT ends it and every window in it, with no confirmation -- hence the
-- guard. Was SUPER+SHIFT+M until 2026-08-17.
--
-- Plain SUPER+M stays unbound for the reason it always was: too easy to hit by
-- accident. Hyprland still falls back to a hardcoded SUPER+M exit if the config
-- fails to load, which remains the real escape hatch, and the rescue
-- hyprland.conf keeps the classic unguarded SUPER+M on purpose.
hl.bind(mainMod .. " + SHIFT + L", hl.dsp.exit())

-- PATH gains ~/.local/bin so hyprshot resolves the slurp shim there, which
-- dresses region select in the active skin (handoff turn 19f).
hl.bind("PRINT",         hl.dsp.exec_cmd('PATH="$HOME/.local/bin:$PATH" hyprshot -m window'))
hl.bind("SHIFT + PRINT", hl.dsp.exec_cmd('PATH="$HOME/.local/bin:$PATH" hyprshot -m region'))

-- exec_cmd runs through sh -c, so pipes and && still work as before.
-- Wrapper rather than an inline pipeline: it renders image entries as actual
-- thumbnails instead of "[[ binary data ... ]]". Absolute path because
-- Hyprland's exec environment does not carry ~/.local/bin on PATH.
hl.bind(mainMod .. " + V", hl.dsp.exec_cmd(os.getenv("HOME") .. "/.local/bin/cliphist-wofi"))
-- SUPER+X (wipe clipboard + history) removed: unguarded, silent, no undo, and
-- one key away from SUPER+C (close window). Run `cliphist wipe` in a terminal
-- for the rare case that needs it.

-- Restart the whole Quickshell shell. pkill rather than `qs kill`: qs kill
-- only takes down the instance it resolves as "current", and a leftover
-- daemon from an earlier config makes every later `qs ipc call` ambiguous
-- -- they hang, and with them every keybind that goes through IPC. Killing
-- by process name guarantees exactly one instance comes back.
hl.bind(mainMod .. " + SHIFT + R", hl.dsp.exec_cmd("pkill -x qs; sleep 0.5; qs -d"))
-- Lock. SUPER+SHIFT+L above is the log-out counterpart.
hl.bind(mainMod .. " + L",         hl.dsp.exec_cmd("qs ipc call lock lock || hyprlock"))

-- Power menu (Quickshell, handoff turn 19a): LOCK / SUSPEND / LOG OUT /
-- SHUT DOWN with a red-framed confirmation on the destructive two.
hl.bind(mainMod .. " + Escape",    hl.dsp.exec_cmd("qs ipc call power toggle"))

-- Details menu (Quickshell, handoff turn 17a): the control panel as a game
-- menu, one layer deep -- SUMMARY / STATS / ABILITIES / ITEMS / MOVES /
-- TRAINABLE / SESSION.
hl.bind(mainMod .. " + D",         hl.dsp.exec_cmd("qs ipc call details toggle"))

-- Color picker. -a copies to clipboard, -n notifies via swaync, -l gives
-- lowercase hex. Drop -n if the notification gets annoying.
hl.bind(mainMod .. " + P", hl.dsp.exec_cmd("hyprpicker -a -f hex -l -n"))

-- Blue-light filter manual override, on top of the hyprsunset.conf schedule.
-- `hyprctl hyprsunset temperature` prints the current value as a bare number,
-- so compare against it: warm if currently neutral, neutral otherwise.
-- Deliberately NOT `hyprctl hyprsunset identity` for the off half -- identity
-- clears the color matrix but leaves the query still reporting the old warm
-- value, so the toggle would latch on and never come back. 6000 is the
-- neutral default and round-trips correctly.
-- The schedule reasserts itself at the next profile boundary either way.
hl.bind(mainMod .. " + SHIFT + N", hl.dsp.exec_cmd(
    "[ \"$(hyprctl hyprsunset temperature)\" -ge 5000 ] " ..
    "&& hyprctl hyprsunset temperature 4000 " ..
    "|| hyprctl hyprsunset temperature 6000"))

-- Move focus with mainMod + arrow keys
hl.bind(mainMod .. " + left",  hl.dsp.focus({ direction = "left" }))
hl.bind(mainMod .. " + right", hl.dsp.focus({ direction = "right" }))
hl.bind(mainMod .. " + up",    hl.dsp.focus({ direction = "up" }))
hl.bind(mainMod .. " + down",  hl.dsp.focus({ direction = "down" }))

-- Workspaces 1-9 plus 0 -> 10. Twenty lines of hyprlang collapse into a loop.
for i = 1, 10 do
    local key = i % 10 -- 10 maps to key 0
    hl.bind(mainMod .. " + " .. key,           hl.dsp.focus({ workspace = i }))
    hl.bind(mainMod .. " + SHIFT + " .. key,   hl.dsp.window.move({ workspace = i }))
end

-- Special workspace (scratchpad)
hl.bind(mainMod .. " + S",         hl.dsp.workspace.toggle_special("magic"))
hl.bind(mainMod .. " + SHIFT + S", hl.dsp.window.move({ workspace = "special:magic" }))

-- Scroll through workspaces with mainMod + scroll
hl.bind(mainMod .. " + mouse_down", hl.dsp.focus({ workspace = "e+1" }))
hl.bind(mainMod .. " + mouse_up",   hl.dsp.focus({ workspace = "e-1" }))

-- Move/resize with mainMod + LMB/RMB (was bindm)
hl.bind(mainMod .. " + mouse:272", hl.dsp.window.drag(),   { mouse = true })
hl.bind(mainMod .. " + mouse:273", hl.dsp.window.resize(), { mouse = true })

-- Laptop multimedia keys (was bindel -> { locked = true, repeating = true })
-- One meter step per press (the trainable pair is 8 steps everywhere, and a
-- press that moves less than a bar is invisible). The shell snaps to the
-- step grid; the fallbacks approximate one step if it is not running.
hl.bind("XF86AudioRaiseVolume",  hl.dsp.exec_cmd("qs ipc call trainable volup || wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 5%+"), { locked = true, repeating = true })
hl.bind("XF86AudioLowerVolume",  hl.dsp.exec_cmd("qs ipc call trainable voldown || wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-"),    { locked = true, repeating = true })
hl.bind("XF86AudioMute",         hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle"),     { locked = true, repeating = true })
hl.bind("XF86AudioMicMute",      hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle"),   { locked = true, repeating = true })
hl.bind("XF86MonBrightnessUp",   hl.dsp.exec_cmd("qs ipc call trainable brightup || brightnessctl -e4 set 12%+"), { locked = true, repeating = true })
hl.bind("XF86MonBrightnessDown", hl.dsp.exec_cmd("qs ipc call trainable brightdown || brightnessctl -e4 set 12%-"), { locked = true, repeating = true })

-- Cycle ASUS platform profile: quiet -> balanced -> performance.
-- Calls a root helper via a NOPASSWD sudoers rule and shows a notification.
-- If you later find which keycode Fn+F5 emits, rebind this to that instead.
hl.bind(mainMod .. " + F5", hl.dsp.exec_cmd("/home/naidoq/.local/bin/profile-cycle-notify"))

-- Requires playerctl (was bindl -> { locked = true })
hl.bind("XF86AudioNext",  hl.dsp.exec_cmd("playerctl next"),       { locked = true })
hl.bind("XF86AudioPause", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })
hl.bind("XF86AudioPlay",  hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })
hl.bind("XF86AudioPrev",  hl.dsp.exec_cmd("playerctl previous"),   { locked = true })


--------------------------------
---- WINDOWS AND WORKSPACES ----
--------------------------------

-- All of yours were commented out. Kept that way, in the new syntax.
-- Note that rules now take a `name` and a `match` table.

-- Persistent workspace assignment. Unlike the exec_cmd workspace prefixes in
-- the autostart block, these apply however the app is launched -- launcher,
-- terminal, tray restore, or a link handler -- not just at login.
--
-- initialClass rather than class: class can change at runtime, initialClass is
-- frozen at window creation, so the rule still matches if the app renames
-- itself later. "silent" means the window goes there without stealing focus.
--
-- The regexes tolerate either capitalization because Electron and Spotify have
-- both shipped either over time. Verify against your actual windows with
-- hyprprop, or:  hyprctl clients -j | jq -r '.[].initialClass'
hl.window_rule({
    name      = "discord-to-9",
    match     = { initial_class = "^([Dd]iscord)$" },
    workspace = "9 silent",
})

hl.window_rule({
    name      = "spotify-to-8",
    match     = { initial_class = "^([Ss]potify)$" },
    workspace = "8 silent",
})

-- hl.window_rule({
--     name  = "float-kitty",
--     match = { class = "^(kitty)$", title = "^(kitty)$" },
--     float = true,
-- })

-- hl.window_rule({
--     name  = "suppress-maximize-events",
--     match = { class = ".*" },
--     suppress_event = "maximize",
-- })

-- hl.window_rule({
--     name  = "fix-xwayland-drags",
--     match = {
--         class      = "^$",
--         title      = "^$",
--         xwayland   = true,
--         float      = true,
--         fullscreen = false,
--         pin        = false,
--     },
--     no_focus = true,
-- })
